spring.application.name=huerta-casera-api

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/huerta_casera
spring.datasource.username=huerta_user
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Endpoints de observabilidad con Spring Boot Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always